version: "3"

services:
  app:
    container_name: discord-chatgpt
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    logging:
      driver: json-file
      options:
        max-size: 50m
